import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const scenes=JSON.parse(await fs.readFile(path.join(root,'src/slides.json'),'utf8'));
for (const scene of scenes) {
  for (const element of scene) {
    if (element.type === 'image') {
      const bytes = await fs.readFile(path.join(root, element.src));
      element.src = 'data:image/png;base64,' + bytes.toString('base64');
    }
  }
}
await fs.mkdir(path.join(root,'output'), {recursive:true});
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const slides=scenes.map((scene,i)=>`<section class="slide ${i===0?'active':''}" aria-label="Slayt ${i+1}" ${i?'inert':''}>${scene.map(o=>o.type==='text'?`<div class="text" style="left:${o.x}px;top:${o.y}px;width:${o.w}px;height:${o.h}px;font-size:${o.size}px;color:${o.color};font-weight:${o.bold?700:400}">${esc(o.t)}</div>`:`<img alt="${esc(o.alt)}" src="${o.src}" style="left:${o.x}px;top:${o.y}px;width:${o.w}px;height:${o.h}px">`).join('')}</section>`).join('');
const html=`<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>inscribi director — Hackathon Sunumu</title><style>
*{box-sizing:border-box}body{margin:0;background:#07080c;color:#f3f5fa;font-family:"Helvetica Neue",Arial,sans-serif;overflow:hidden}#stage{position:absolute;width:1280px;height:720px;transform-origin:0 0;background:#0b0d12}.slide{position:absolute;inset:0;opacity:0;pointer-events:none;transition:opacity .18s ease}.slide.active{opacity:1;pointer-events:auto}.text{position:absolute;white-space:pre-wrap;line-height:1.17;display:flex;align-items:center}img{position:absolute;object-fit:contain}nav{position:fixed;bottom:10px;left:50%;transform:translateX(-50%);display:flex;gap:7px;padding:8px;background:#151923e8;border:1px solid #2a3142;border-radius:12px;opacity:0;transition:opacity .2s}body.controls nav,nav:hover,nav:focus-within{opacity:1}button,a{background:#252a39;color:#f3f5fa;border:0;border-radius:7px;font:14px "Helvetica Neue",Arial;padding:9px 14px;text-decoration:none;cursor:pointer}button:hover,a:hover{background:#534373}#count{padding:9px 6px;font-size:14px}button:focus-visible,a:focus-visible{outline:2px solid #b69af7}@media print{body{overflow:visible;background:#0b0d12}#stage{position:static;transform:none!important;width:1280px;height:auto}.slide{position:relative;opacity:1;height:720px;page-break-after:always}nav{display:none}@page{size:1280px 720px;margin:0}}
</style></head><body><main id="stage">${slides}</main><nav aria-label="Sunum kontrolleri"><button id="prev" aria-label="Önceki slayt">←</button><span id="count">1 / 6</span><button id="next" aria-label="Sonraki slayt">→</button><button id="full">Tam ekran</button><a href="https://live.inscribi.com/stage" target="_blank" rel="noopener">Canlı sahne ↗</a></nav><script>
let index=Math.min(5,Math.max(0,Number(location.hash.slice(1)||1)-1));const slides=[...document.querySelectorAll('.slide')];function show(n){index=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.classList.toggle('active',i===index);s.inert=i!==index});document.querySelector('#count').textContent=(index+1)+' / '+slides.length;history.replaceState(null,'','#'+(index+1));}function size(){let s=Math.min(innerWidth/1280,innerHeight/720);Object.assign(document.querySelector('#stage').style,{transform:'scale('+s+')',left:(innerWidth-1280*s)/2+'px',top:(innerHeight-720*s)/2+'px'});}document.querySelector('#prev').onclick=()=>show(index-1);document.querySelector('#next').onclick=()=>show(index+1);function full(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}document.querySelector('#full').onclick=full;addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(index+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(index-1)}if(e.key==='Home')show(0);if(e.key==='End')show(5);if(e.key.toLowerCase()==='f')full()});let timer;addEventListener('pointermove',()=>{document.body.classList.add('controls');clearTimeout(timer);timer=setTimeout(()=>document.body.classList.remove('controls'),1800)});let tx=0;addEventListener('touchstart',e=>tx=e.touches[0].clientX,{passive:true});addEventListener('touchend',e=>{let d=e.changedTouches[0].clientX-tx;if(Math.abs(d)>70)show(index+(d<0?1:-1))},{passive:true});addEventListener('resize',size);show(index);size();
</script></body></html>`;
await fs.writeFile(root+'/output/inscribi-sunum.html',html);console.log('HTML ready');
